### PR TITLE
Parse bool type correctly. Parse integer and bool example. Set enum type

### PR DESCRIPTION
**Pull request by joejoe321321**
to string, it is required to make enum visible in swagger.

### CODE REVIEW

**Comment by joejoe321321** [comment]
e.g.
https://joejoe321321.github.io/test_mkdocs/site/?url=https://joejoe321321.github.io/Test/cupid_swagger.json

**Comment by shichung** [comment]
👍

**Comment by shichung** [comment]
@chinkong83 
could you help also take a look?

**Comment by chinkong83** [comment]
不確定 @joejoe321321 有沒有時間，希望可以補 test case，我想把這邊的 test 慢慢補起來。喔，就只有針對現在你們講的 case 這個去補 test 就好了

**Comment by joejoe321321** [comment]
可以呀, 我試著補補看

**Comment by chinkong83** [comment]
ok

**Pull request merged**
