### PR TITLE
update ardielle/ardielle-go in vendor to 1d359529d1f92b8c1dfe56c39548…

### PR DESCRIPTION
**Pull request by joejoe321321**
…a5f96851cc29

### CODE REVIEW

**Comment by shichung** [comment]
the commit
https://github.com/ardielle/ardielle-go/commit/1d359529d1f92b8c1dfe56c39548a5f96851cc29

**Comment by shichung** [comment]
the previous updates in this repository
https://github.com/yahoo/parsec-rdl-gen/blob/master/vendor/github.com/ardielle/ardielle-go/rdl/util.go#L302-L303
https://github.com/yahoo/parsec-rdl-gen/blob/master/vendor/github.com/ardielle/ardielle-go/rdl/util.go#L390-L391

**Comment by shichung** [comment]
it is ok for me

just curious @joejoe321321 used the vendor tool to import these changes or not?

**Comment by shichung** [comment]
@chinkong83 
could you also help review it?
thanks

**Comment by chinkong83** [comment]
LGTM,

**Pull request merged**
